### ISSUE TITLE
How write a dump ?

### ISSUE THREAD

**Issue by doudz** [giacomoferretti/nfc-srix-tools#1]
I just give a try and it looks very promising ! :+1: 
Is it possible to write a dump to the same srix key ? and/or another key ?

**Comment by giacomoferretti** [comment]
Yes, I am implementing it now :wink:

**Comment by giacomoferretti** [comment]
Done!

**Comment by doudz** [comment]
Really fast !

**Comment by doudz** [comment]
After flashing a dump, my key isn't recognize by a third machine, is there a protection on eeprom data ?

restoring the previous dump, my key is working again

what I've done:
- make dump #1
- insert the key on third machine that write something on key
- make new dump #2
- restore dump #1
- insert the key on machine again -> the key isn't recognized anymore
- restore dump #2
-> the key is working again on the machine

**Comment by doudz** [comment]
data on the key are probably encrypted using the counter...

**Comment by giacomoferretti** [comment]
It depends. Could you tell me exactly which machine are you talking about?

**Comment by doudz** [comment]
a vending machine using coges key
