### ISSUE TITLE
Skip confirmation

### ISSUE THREAD

**Issue by doudz** [giacomoferretti/nfc-srix-tools#4]
Would it be possible to add an argument to srix-restore in order to skip write confirmation ?
for example 
`srix-restore -y myfile`

to avoid :
```
This action is irreversible.
Are you sure? [Y/N] y
```

**Comment by giacomoferretti** [comment]
Yes, it should pretty easy to add, but I haven't touched the project for a while now and I think there are some bugs. I'm gonna do it in the next few days, I don't have that much spare time 😕

**Comment by giacomoferretti** [comment]
Also @doudz, can you send me an email at me@hexile.me to discuss some things privately?

**Comment by giacomoferretti** [comment]
Just out of curiosity, which reader are you using?
I was thinking of writing a custom userspace driver for the ACR122U (and the PN532 in the future) so I can remove the libnfc dependency.

**Comment by doudz** [comment]
I'm using a ACR122U reader
https://fr.aliexpress.com/item/32842162683.html?spm=a2g0s.9042311.0.0.27426c37tpATm8
